<?php

return [
    'AED' => ['symbol' => 'د.إ', 'name' => '{"en":"United Arab Emirates Dirham"}'],
    'AFN' => ['symbol' => '؋', 'name' => '{"en":"Afghan Afghani"}'],
    'ALL' => ['symbol' => 'L', 'name' => '{"en":"Albanian Lek"}'],
    'AMD' => ['symbol' => '֏', 'name' => '{"en":"Armenian Dram"}'],
    'ANG' => ['symbol' => 'ƒ', 'name' => '{"en":"Netherlands Antillean Guilder"}'],
    'AOA' => ['symbol' => 'Kz', 'name' => '{"en":"Angolan Kwanza"}'],
    'ARS' => ['symbol' => '$', 'name' => '{"en":"Argentine Peso"}'],
    'AUD' => ['symbol' => 'A$', 'name' => '{"en":"Australian Dollar"}'],
    'AWG' => ['symbol' => 'ƒ', 'name' => '{"en":"Aruban Florin"}'],
    'AZN' => ['symbol' => '₼', 'name' => '{"en":"Azerbaijani Manat"}'],
    'BAM' => ['symbol' => 'KM', 'name' => '{"en":"Bosnia-Herzegovina Convertible Mark"}'],
    'BBD' => ['symbol' => '$', 'name' => '{"en":"Barbadian Dollar"}'],
    'BDT' => ['symbol' => '৳', 'name' => '{"en":"Bangladeshi Taka"}'],
    'BGN' => ['symbol' => 'лв', 'name' => '{"en":"Bulgarian Lev"}'],
    'BHD' => ['symbol' => '.د.ب', 'name' => '{"en":"Bahraini Dinar"}'],
    'BIF' => ['symbol' => 'FBu', 'name' => '{"en":"Burundian Franc"}'],
    'BMD' => ['symbol' => '$', 'name' => '{"en":"Bermudian Dollar"}'],
    'BND' => ['symbol' => '$', 'name' => '{"en":"Brunei Dollar"}'],
    'BOB' => ['symbol' => 'Bs', 'name' => '{"en":"Bolivian Boliviano"}'],
    'BRL' => ['symbol' => 'R$', 'name' => '{"en":"Brazilian Real"}'],
    'BSD' => ['symbol' => '$', 'name' => '{"en":"Bahamian Dollar"}'],
    'BTN' => ['symbol' => 'Nu.', 'name' => '{"en":"Bhutanese Ngultrum"}'],
    'BWP' => ['symbol' => 'P', 'name' => '{"en":"Botswana Pula"}'],
    'BYN' => ['symbol' => 'Br', 'name' => '{"en":"Belarusian Ruble"}'],
    'BZD' => ['symbol' => 'BZ$', 'name' => '{"en":"Belize Dollar"}'],
    'CAD' => ['symbol' => 'C$', 'name' => '{"en":"Canadian Dollar"}'],
    'CDF' => ['symbol' => 'FC', 'name' => '{"en":"Congolese Franc"}'],
    'CHF' => ['symbol' => 'CHF', 'name' => '{"en":"Swiss Franc"}'],
    'CLP' => ['symbol' => '$', 'name' => '{"en":"Chilean Peso"}'],
    'CNY' => ['symbol' => '¥', 'name' => '{"en":"Chinese Yuan"}'],
    'COP' => ['symbol' => '$', 'name' => '{"en":"Colombian Peso"}'],
    'CRC' => ['symbol' => '₡', 'name' => '{"en":"Costa Rican Colón"}'],
    'CUC' => ['symbol' => '$', 'name' => '{"en":"Cuban Convertible Peso"}'],
    'CUP' => ['symbol' => '$', 'name' => '{"en":"Cuban Peso"}'],
    'CVE' => ['symbol' => '$', 'name' => '{"en":"Cape Verdean Escudo"}'],
    'CZK' => ['symbol' => 'Kč', 'name' => '{"en":"Czech Koruna"}'],
    'DJF' => ['symbol' => 'Fdj', 'name' => '{"en":"Djiboutian Franc"}'],
    'DKK' => ['symbol' => 'kr', 'name' => '{"en":"Danish Krone"}'],
    'DOP' => ['symbol' => 'RD$', 'name' => '{"en":"Dominican Peso"}'],
    'DZD' => ['symbol' => 'د.ج', 'name' => '{"en":"Algerian Dinar"}'],
    'EGP' => ['symbol' => '£', 'name' => '{"en":"Egyptian Pound"}'],
    'ERN' => ['symbol' => 'Nfk', 'name' => '{"en":"Eritrean Nakfa"}'],
    'ETB' => ['symbol' => 'Br', 'name' => '{"en":"Ethiopian Birr"}'],
    'EUR' => ['symbol' => '€', 'name' => '{"en":"Euro"}'],
    'FJD' => ['symbol' => 'FJ$', 'name' => '{"en":"Fijian Dollar"}'],
    'FKP' => ['symbol' => '£', 'name' => '{"en":"Falkland Islands Pound"}'],
    'GBP' => ['symbol' => '£', 'name' => '{"en":"British Pound Sterling"}'],
    'GEL' => ['symbol' => '₾', 'name' => '{"en":"Georgian Lari"}'],
    'GHS' => ['symbol' => '₵', 'name' => '{"en":"Ghanaian Cedi"}'],
    'GIP' => ['symbol' => '£', 'name' => '{"en":"Gibraltar Pound"}'],
    'GMD' => ['symbol' => 'D', 'name' => '{"en":"Gambian Dalasi"}'],
    'GNF' => ['symbol' => 'FG', 'name' => '{"en":"Guinean Franc"}'],
    'GTQ' => ['symbol' => 'Q', 'name' => '{"en":"Guatemalan Quetzal"}'],
    'GYD' => ['symbol' => '$', 'name' => '{"en":"Guyanese Dollar"}'],
    'HKD' => ['symbol' => 'HK$', 'name' => '{"en":"Hong Kong Dollar"}'],
    'HNL' => ['symbol' => 'L', 'name' => '{"en":"Honduran Lempira"}'],
    'HTG' => ['symbol' => 'G', 'name' => '{"en":"Haitian Gourde"}'],
    'HUF' => ['symbol' => 'Ft', 'name' => '{"en":"Hungarian Forint"}'],
    'IDR' => ['symbol' => 'Rp', 'name' => '{"en":"Indonesian Rupiah"}'],
    'ILS' => ['symbol' => '₪', 'name' => '{"en":"Israeli New Shekel"}'],
    'INR' => ['symbol' => '₹', 'name' => '{"en":"Indian Rupee"}'],
    'IQD' => ['symbol' => 'ع.د', 'name' => '{"en":"Iraqi Dinar"}'],
    'IRR' => ['symbol' => '﷼', 'name' => '{"en":"Iranian Rial"}'],
    'ISK' => ['symbol' => 'kr', 'name' => '{"en":"Icelandic Króna"}'],
    'JMD' => ['symbol' => 'J$', 'name' => '{"en":"Jamaican Dollar"}'],
    'JOD' => ['symbol' => 'د.ا', 'name' => '{"en":"Jordanian Dinar"}'],
    'JPY' => ['symbol' => '¥', 'name' => '{"en":"Japanese Yen"}'],
    'KES' => ['symbol' => 'KSh', 'name' => '{"en":"Kenyan Shilling"}'],
    'KGS' => ['symbol' => 'лв', 'name' => '{"en":"Kyrgyzstani Som"}'],
    'KHR' => ['symbol' => '៛', 'name' => '{"en":"Cambodian Riel"}'],
    'KMF' => ['symbol' => 'CF', 'name' => '{"en":"Comorian Franc"}'],
    'KPW' => ['symbol' => '₩', 'name' => '{"en":"North Korean Won"}'],
    'KRW' => ['symbol' => '₩', 'name' => '{"en":"South Korean Won"}'],
    'KWD' => ['symbol' => 'د.ك', 'name' => '{"en":"Kuwaiti Dinar"}'],
    'KYD' => ['symbol' => '$', 'name' => '{"en":"Cayman Islands Dollar"}'],
    'KZT' => ['symbol' => '₸', 'name' => '{"en":"Kazakhstani Tenge"}'],
    'LAK' => ['symbol' => '₭', 'name' => '{"en":"Lao Kip"}'],
    'LBP' => ['symbol' => 'ل.ل', 'name' => '{"en":"Lebanese Pound"}'],
    'LKR' => ['symbol' => 'Rs', 'name' => '{"en":"Sri Lankan Rupee"}'],
    'LRD' => ['symbol' => '$', 'name' => '{"en":"Liberian Dollar"}'],
    'LSL' => ['symbol' => 'L', 'name' => '{"en":"Lesotho Loti"}'],
    'LYD' => ['symbol' => 'ل.د', 'name' => '{"en":"Libyan Dinar"}'],
    'MAD' => ['symbol' => 'د.م.', 'name' => '{"en":"Moroccan Dirham"}'],
    'MDL' => ['symbol' => 'L', 'name' => '{"en":"Moldovan Leu"}'],
    'MGA' => ['symbol' => 'Ar', 'name' => '{"en":"Malagasy Ariary"}'],
    'MKD' => ['symbol' => 'ден', 'name' => '{"en":"Macedonian Denar"}'],
    'MMK' => ['symbol' => 'K', 'name' => '{"en":"Myanmar Kyat"}'],
    'MNT' => ['symbol' => '₮', 'name' => '{"en":"Mongolian Tögrög"}'],
    'MOP' => ['symbol' => 'MOP$', 'name' => '{"en":"Macanese Pataca"}'],
    'MRU' => ['symbol' => 'UM', 'name' => '{"en":"Mauritanian Ouguiya"}'],
    'MUR' => ['symbol' => '₨', 'name' => '{"en":"Mauritian Rupee"}'],
    'MVR' => ['symbol' => 'Rf', 'name' => '{"en":"Maldivian Rufiyaa"}'],
    'MWK' => ['symbol' => 'MK', 'name' => '{"en":"Malawian Kwacha"}'],
    'MXN' => ['symbol' => '$', 'name' => '{"en":"Mexican Peso"}'],
    'MYR' => ['symbol' => 'RM', 'name' => '{"en":"Malaysian Ringgit"}'],
    'MZN' => ['symbol' => 'MT', 'name' => '{"en":"Mozambican Metical"}'],
    'NAD' => ['symbol' => '$', 'name' => '{"en":"Namibian Dollar"}'],
    'NGN' => ['symbol' => '₦', 'name' => '{"en":"Nigerian Naira"}'],
    'NIO' => ['symbol' => 'C$', 'name' => '{"en":"Nicaraguan Córdoba"}'],
    'NOK' => ['symbol' => 'kr', 'name' => '{"en":"Norwegian Krone"}'],
    'NPR' => ['symbol' => '₨', 'name' => '{"en":"Nepalese Rupee"}'],
    'NZD' => ['symbol' => 'NZ$', 'name' => '{"en":"New Zealand Dollar"}'],
    'OMR' => ['symbol' => 'ر.ع.', 'name' => '{"en":"Omani Rial"}'],
    'PAB' => ['symbol' => 'B/.', 'name' => '{"en":"Panamanian Balboa"}'],
    'PEN' => ['symbol' => 'S/.', 'name' => '{"en":"Peruvian Sol"}'],
    'PGK' => ['symbol' => 'K', 'name' => '{"en":"Papua New Guinean Kina"}'],
    'PHP' => ['symbol' => '₱', 'name' => '{"en":"Philippine Peso"}'],
    'PKR' => ['symbol' => '₨', 'name' => '{"en":"Pakistani Rupee"}'],
    'PLN' => ['symbol' => 'zł', 'name' => '{"en":"Polish Złoty"}'],
    'PYG' => ['symbol' => '₲', 'name' => '{"en":"Paraguayan Guaraní"}'],
    'QAR' => ['symbol' => '﷼', 'name' => '{"en":"Qatari Riyal"}'],
    'RON' => ['symbol' => 'lei', 'name' => '{"en":"Romanian Leu"}'],
    'RSD' => ['symbol' => 'дин.', 'name' => '{"en":"Serbian Dinar"}'],
    'RUB' => ['symbol' => '₽', 'name' => '{"en":"Russian Ruble"}'],
    'RWF' => ['symbol' => 'FRw', 'name' => '{"en":"Rwandan Franc"}'],
    'SAR' => ['symbol' => '﷼', 'name' => '{"en":"Saudi Riyal"}'],
    'SBD' => ['symbol' => '$', 'name' => '{"en":"Solomon Islands Dollar"}'],
    'SCR' => ['symbol' => '₨', 'name' => '{"en":"Seychellois Rupee"}'],
    'SDG' => ['symbol' => '£', 'name' => '{"en":"Sudanese Pound"}'],
    'SEK' => ['symbol' => 'kr', 'name' => '{"en":"Swedish Krona"}'],
    'SGD' => ['symbol' => 'S$', 'name' => '{"en":"Singapore Dollar"}'],
    'SHP' => ['symbol' => '£', 'name' => '{"en":"Saint Helena Pound"}'],
    'SLL' => ['symbol' => 'Le', 'name' => '{"en":"Sierra Leonean Leone"}'],
    'SOS' => ['symbol' => 'Sh', 'name' => '{"en":"Somali Shilling"}'],
    'SRD' => ['symbol' => '$', 'name' => '{"en":"Surinamese Dollar"}'],
    'SSP' => ['symbol' => '£', 'name' => '{"en":"South Sudanese Pound"}'],
    'STN' => ['symbol' => 'Db', 'name' => '{"en":"São Tomé and Príncipe Dobra"}'],
    'SYP' => ['symbol' => '£', 'name' => '{"en":"Syrian Pound"}'],
    'SZL' => ['symbol' => 'L', 'name' => '{"en":"Swazi Lilangeni"}'],
    'THB' => ['symbol' => '฿', 'name' => '{"en":"Thai Baht"}'],
    'TJS' => ['symbol' => 'ЅМ', 'name' => '{"en":"Tajikistani Somoni"}'],
    'TMT' => ['symbol' => 'm', 'name' => '{"en":"Turkmenistani Manat"}'],
    'TND' => ['symbol' => 'د.ت', 'name' => '{"en":"Tunisian Dinar"}'],
    'TOP' => ['symbol' => 'T$', 'name' => '{"en":"Tongan Paʻanga"}'],
    'TRY' => ['symbol' => '₺', 'name' => '{"en":"Turkish Lira"}'],
    'TTD' => ['symbol' => 'TT$', 'name' => '{"en":"Trinidad and Tobago Dollar"}'],
    'TWD' => ['symbol' => 'NT$', 'name' => '{"en":"New Taiwan Dollar"}'],
    'TZS' => ['symbol' => 'Sh', 'name' => '{"en":"Tanzanian Shilling"}'],
    'UAH' => ['symbol' => '₴', 'name' => '{"en":"Ukrainian Hryvnia"}'],
    'UGX' => ['symbol' => 'Sh', 'name' => '{"en":"Ugandan Shilling"}'],
    'USD' => ['symbol' => '$', 'name' => '{"en":"United States Dollar"}'],
    'UYU' => ['symbol' => '$', 'name' => '{"en":"Uruguayan Peso"}'],
    'UZS' => ['symbol' => 'soʻm', 'name' => '{"en":"Uzbekistani Som"}'],
    'VES' => ['symbol' => 'Bs.S', 'name' => '{"en":"Venezuelan Bolívar"}'],
    'VND' => ['symbol' => '₫', 'name' => '{"en":"Vietnamese Dong"}'],
    'VUV' => ['symbol' => 'VT', 'name' => '{"en":"Vanuatu Vatu"}'],
    'WST' => ['symbol' => 'WS$', 'name' => '{"en":"Samoan Tala"}'],
    'XAF' => ['symbol' => 'FCFA', 'name' => '{"en":"Central African CFA Franc"}'],
    'XCD' => ['symbol' => 'EC$', 'name' => '{"en":"East Caribbean Dollar"}'],
    'XOF' => ['symbol' => 'CFA', 'name' => '{"en":"West African CFA Franc"}'],
    'XPF' => ['symbol' => '₣', 'name' => '{"en":"CFP Franc"}'],
    'YER' => ['symbol' => '﷼', 'name' => '{"en":"Yemeni Rial"}'],
    'ZAR' => ['symbol' => 'R', 'name' => '{"en":"South African Rand"}'],
    'ZMW' => ['symbol' => 'ZK', 'name' => '{"en":"Zambian Kwacha"}'],
];
